namespace LocalVectorDB.Models
{
    /// <summary>
    /// Represents a search request containing the query vector and the number of top results to return.
    /// </summary>
    public record SearchRequest(List<double> QueryVector, int TopK);

    /// <summary>
    /// Represents a vector item stored in the database.
    /// </summary>
    public class VectorItem
    {
        /// <summary>
        /// Unique identifier for the vector item (automatically generated by LiteDB).
        /// </summary>
        public int Id { get; set; }  // Primary key for the vector

        /// <summary>
        /// The high-dimensional vector data.
        /// </summary>
        public List<double> Vector { get; set; }  // List of double values representing the vector
    }
}
